### ISSUE TITLE
GanttProject not working on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by CulpeperMike** [bardsoftware/ganttproject#2591]
Ganttproject did not copy over on upgrade from Ubuntu 22.04 to 24.04. New deb install not working - no display, no start. Appears to be java problem. I downloaded and installed full JRE bellsoft-java-17-runtime-full but still no joy....

**Comment by dbarashev** [comment]
Please share the contents of `/tmp/ganttproject-launch.log` file after running `ganttproject` command

**Comment by EureDudeheit** [comment]
I also use Ubuntu 24.04 and have the same Issue. Ganttproject starts but i am unable to work with it.

- when i open an existing project and try o manipulate anything, the UI shakes and it hangs. No log is written
- when i create a new project and want to add columns it freezes and can only be killed via bash
- both logs *.ganttproject.d/logs/* and */tmp/ganttproject-launch.log* are not created

### What i tried so far
different versions of JRE (Oracle, OpenJDK...) -> seems not to make any differences.

### Outputs

running ganttproject via bash says:

```
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-exports
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime build
FEIN: We will run with the following plugins:
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin org.ganttproject.chart.pert-3.3.3312 at /usr/share/ganttproject/plugins/base/org.ganttproject.chart.pert/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.impex.msproject2-3.3.3312 at /usr/share/ganttproject/plugins/base/biz.ganttproject.impex.msproject2/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.app.localization-3.3.3312 at /usr/share/ganttproject/plugins/base/biz.ganttproject.app.localization/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.impex.ical-3.3.3312 at /usr/share/ganttproject/plugins/base/biz.ganttproject.impex.ical/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin org.ganttproject.impex.htmlpdf-3.3.3312 at /usr/share/ganttproject/plugins/base/org.ganttproject.impex.htmlpdf/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin net.sourceforge.ganttproject-3.3.3312 at /usr/share/ganttproject/plugins/base/ganttproject/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.app.libs-3.3.3312 at /usr/share/ganttproject/plugins/base/biz.ganttproject.app.libs/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.ModuleRuntime lambda$build$3
FEIN: Plugin biz.ganttproject.core-3.3.3312 at /usr/share/ganttproject/plugins/base/biz.ganttproject.core/plugin.xml
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.Runner run
FEIN: Command line args: [-log, true, -log_file, /home/felix/.ganttproject.d/logs/.ganttproject-20241030115032.log]
Okt. 30, 2024 11:50:33 AM com.bardsoftware.eclipsito.runtime.Runner run
FEIN: Launching application=net.sourceforge.ganttproject.GanttProject
[2024-10-30 11:50:33] [WARN][javafx] Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1bb123db' 
```

*ganttproject -v* says:

```
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.base specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.controls specified to --add-exports
WARNING: Unknown module: javafx.graphics specified to --add-exports
Exception in thread "main" com.beust.jcommander.ParameterException: Expected a value after parameter -v
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:925)
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at com.bardsoftware.eclipsito.Launch.main(Launch.java:21)

Searching for Java in /usr/share/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...found openjdk version "17.0.12" 2024-07-16
JAVA_HOME=
JAVA_COMMAND=/usr/bin/java
GP_HOME=/usr/share/ganttproject
user.dir=/home/felix

Searching for Java in /usr/share/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...found openjdk version "17.0.12" 2024-07-16
JAVA_HOME=
JAVA_COMMAND=/usr/bin/java
GP_HOME=/usr/share/ganttproject
user.dir=/home/felix
```

**Comment by dbarashev** [comment]
Did you try installing Liberica Java 17 Full JRE from BellSoft? I recommend doing it using [sdkman!](https://sdkman.io/) (because it allows for easy switching between different Java runtimes) however you may as well download it directly from BellSoft site: https://download.bell-sw.com/java/17.0.13+12/bellsoft-jre17.0.13+12-linux-amd64-full.deb

**Comment by EureDudeheit** [comment]
Yes. I tried to open a project (only one task, nothing else). The app flickers and i only can kill it via bash. The logfile is as follows:

[ganttproject-20241030122051.log](https://github.com/user-attachments/files/17571363/ganttproject-20241030122051.log)

**Comment by dbarashev** [comment]
And what is in /tmp/ganttproject-launcher.log ?

**Comment by EureDudeheit** [comment]
```
Searching for Java in /usr/share/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...found openjdk version "17.0.13" 2024-10-15 LTS
JAVA_HOME=
JAVA_COMMAND=/usr/bin/java
GP_HOME=/usr/share/ganttproject
user.dir=/home/felix/OneDrive/Projekte/Hauskauf/Planung/08_Terminplan
```

**Comment by dbarashev** [comment]
> The app flickers and i only can kill it via bash. 

How does it look like? Can you record a screencast?

**Comment by EureDudeheit** [comment]
I would have to reinstall another JRE, is this neccessarry for You?

**Comment by EureDudeheit** [comment]
That flickering (was like when you grab the window and wobble it) occured with Liberica 17 Full JRE as well as with OpenJDK and Oracle Java.
[ganttproject-20241030161223.log](https://github.com/user-

https://github.com/user-attachments/assets/bc445f4d-dec5-4640-a5ab-16653b02a70b

attachments/files/17575117/ganttproject-20241030161223.log)

**Comment by dbarashev** [comment]
Nice ) Did you try changing the appearance/font/window size/monitor? I mean, this looks as if something is wrong somewhere in the depth of the UI libraries, and is quite specific to your setup. Also, I recommend trying our ZIP distro (it completely relies on the JavaFX from JRE while DEB is bundled with JavaFX) and Java 21 (probably a bug that causes flickering is fixed there)

**Comment by EureDudeheit** [comment]
I tried your suggestions:

**UI**
- changed apperance to *Nimbus* (was GTK+ before)
- set DPI to 96 (i have a monitor with UHD so everything is very small)

It seems to work now. I will report when there are changes and try the ZIP distro then as well.

a little OT:
Is there a way to change the font size in the timeline?

<img width="568" alt="grafik" src="https://github.com/user-attachments/assets/a414593e-7d2f-4941-97dd-43a00aef8d8c">

**Comment by Slava0135** [comment]
I installed `Azul Zulu JDK` on Arch, but still can't run the app
![image](https://github.com/user-attachments/assets/777d8ef4-da3a-4231-b1fd-9cff4cf61484)

**Comment by dbarashev** [comment]
> I installed `Azul Zulu JDK` on Arch, but still can't run the app 

You need a JRE 17 with FX modules. In case of Azul, here is a link to their packages: https://www.azul.com/downloads/?version=java-17-lts&os=linux&package=jre-fx#zulu

**Comment by fds2610** [comment]
ok, i encounter the same problem. I am newbie to java stuff.
ganttproject launch stopps after splash screen and i have to hit CTRL_C to get back to my bash.

output:

Aug. 25, 2025 9:09:05 AM com.bardsoftware.eclipsito.runtime.Runner run
FEIN: Command line args: [-log, true, -log_file, /home/fds/.ganttproject.d/logs/.ganttproject-20250825090904.log]
Aug. 25, 2025 9:09:05 AM com.bardsoftware.eclipsito.runtime.Runner run
FEIN: Launching application=net.sourceforge.ganttproject.GanttProject
[2025-08-25 09:09:05] [WARN][javafx] Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6de1c6de'  
^C <--- hit by me as ganttproject is not starting...

The log was written to /home/fds/.ganttproject.d/logs/.ganttproject-20250825090904.log

Searching for Java in /usr/share/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...found openjdk version "17.0.15" 2025-04-15
JAVA_HOME=
JAVA_COMMAND=/usr/bin/java
GP_HOME=/usr/share/ganttproject
user.dir=/home/fds

Searching for Java in /usr/share/ganttproject/runtime/bin/java
...missing or not executable
Searching for Java in /usr/bin/java
...found openjdk version "17.0.15" 2025-04-15
JAVA_HOME=
JAVA_COMMAND=/usr/bin/java
GP_HOME=/usr/share/ganttproject
user.dir=/home/fds

mentioned LOG:

GanttProject 3.3.3316
Settings file:
        location: /home/fds/.ganttproject
        size:0
        is readable: false
java.class.path: :/usr/share/ganttproject/eclipsito.jar:/usr/share/ganttproject/lib/slf4j-api-2.0.4.jar:/usr/share/ganttproject/lib/slf4j-jdk14-2.0.4.jar:/usr/share/ganttproject
java.home: /usr/lib/jvm/java-17-openjdk-amd64
java.ext.dirs: null
java.io.tmpdir: /tmp
java.runtime.version: 17.0.15+6-Debian-1
java.vendor: Debian
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.vendor: Debian
java.vm.version: 17.0.15+6-Debian-1
os.arch: amd64
os.name: Linux  (BTW: I am on Debian Testing)
os.version: 6.12.17-amd64
sun.java.command: com.bardsoftware.eclipsito.Launch --app net.sourceforge.ganttproject.GanttProject --version-dirs /usr/share/ganttproject/plugins:~/.ganttproject.d/updates -log true -log_file /home/fds/.ganttproject.d/logs/.ganttproject-20250825090904.log
user.country: DE
user.dir: /home/fds
user.home: /home/fds
user.language: de
user.timezone: Europe/Berlin

**Comment by dbarashev** [comment]
I recommend installing Java 17 with JavaFX modules from BellSoft. This distro is called "Full JRE" on their web site, Here is a direct link: https://download.bell-sw.com/java/17.0.16+12/bellsoft-jre17.0.16+12-linux-amd64-full.deb
